DELIMITER //
DROP TRIGGER IF EXISTS albumaEzabatu //
CREATE TRIGGER albumaEzabatu
BEFORE DELETE ON albumak FOR EACH ROW
BEGIN
	DELETE FROM argazkiak WHERE AlbumID = OLD.ID;
	DELETE FROM albumatzipenzerrenda WHERE AlbumID = OLD.ID;
END; //